// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using payment_system.Infrastructure.Persistence.Contexts;

#nullable disable

namespace payment_system.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("payment_system.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Account_AccountNumber_Format", "length([AccountNumber]) = 26 AND [AccountNumber] NOT GLOB '*[^0-9]*'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b5c-9d8e-1f2a3b4c5d6e"),
                            AccountNumber = "TR1234567890",
                            Balance = 10000m,
                            CreatedAt = new DateTime(2026, 3, 4, 18, 37, 1, 841, DateTimeKind.Utc).AddTicks(4150),
                            Currency = "TRY",
                            CustomerId = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CVC")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.ToTable("Cards", null, t =>
                        {
                            t.HasCheckConstraint("CK_Card_CVC_Format", "length([CVC]) = 3 AND [CVC] NOT GLOB '*[^0-9]*'");

                            t.HasCheckConstraint("CK_Card_CardNumber_Format", "length([CardNumber]) = 16 AND [CardNumber] NOT GLOB '*[^0-9]*'");

                            t.HasCheckConstraint("CK_Card_ExpirationDate_Format", "length([ExpirationDate]) = 5 AND [ExpirationDate] LIKE '__/__' AND [ExpirationDate] NOT LIKE '%[^0-9/]%'");
                        });
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("Customers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Customer_NationalId_Format", "length(NationalId) = 11 AND NationalId NOT GLOB '*[^0-9]*'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d"),
                            CreatedAt = new DateTime(2026, 3, 4, 18, 37, 1, 841, DateTimeKind.Utc).AddTicks(1450),
                            Email = "floyd@example.com",
                            IsDeleted = false,
                            Name = "Floyd",
                            NationalId = "12345678901",
                            Surname = "Pro"
                        });
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ReferenceTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CardId");

                    b.HasIndex("ReferenceTransactionId");

                    b.ToTable("Transactions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c5d-8e9f-2a3b4c5d6e7f"),
                            AccountId = new Guid("b2c3d4e5-f6a7-4b5c-9d8e-1f2a3b4c5d6e"),
                            Amount = 500.00m,
                            CreatedAt = new DateTime(2026, 3, 4, 18, 37, 1, 841, DateTimeKind.Utc).AddTicks(4960),
                            Description = "Market Alışverişi",
                            IsDeleted = false,
                            Status = 1,
                            TransactionDate = new DateTime(2026, 3, 4, 16, 37, 1, 841, DateTimeKind.Utc).AddTicks(4680),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d5e-9f0a-3b4c5d6e7f8a"),
                            AccountId = new Guid("b2c3d4e5-f6a7-4b5c-9d8e-1f2a3b4c5d6e"),
                            Amount = 100.00m,
                            CreatedAt = new DateTime(2026, 3, 4, 18, 37, 1, 841, DateTimeKind.Utc).AddTicks(5100),
                            Description = "Ürün İadesi",
                            IsDeleted = false,
                            ReferenceTransactionId = new Guid("c3d4e5f6-a7b8-4c5d-8e9f-2a3b4c5d6e7f"),
                            Status = 1,
                            TransactionDate = new DateTime(2026, 3, 4, 17, 37, 1, 841, DateTimeKind.Utc).AddTicks(5000),
                            TransactionType = 2
                        });
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Account", b =>
                {
                    b.HasOne("payment_system.Domain.Entities.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Card", b =>
                {
                    b.HasOne("payment_system.Domain.Entities.Account", "Account")
                        .WithMany("Cards")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("payment_system.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("payment_system.Domain.Entities.Card", "Card")
                        .WithMany("Transactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("payment_system.Domain.Entities.Transaction", "ReferenceTransaction")
                        .WithMany("ChildTransactions")
                        .HasForeignKey("ReferenceTransactionId");

                    b.Navigation("Account");

                    b.Navigation("Card");

                    b.Navigation("ReferenceTransaction");
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Account", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Card", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("payment_system.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("ChildTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
